version: 2
jobs:
  deploy:
    docker:
      - image: debian:stretch
    filters:
      branches:
        only: master
    steps:
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
