version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
        name: Install Python deps in a venv
        command: npm install
      - deploy:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN