machine:
  node:
    version: 8.9.1

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
    - bin

test:
  override
    - yarn run build

deployment:
  s3up:
    branch: master
    commands:
      - ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN