defaults: &defaults
  working_directory: .
  docker:
    - image: circleci/node:8.9-stretch

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Build Vue for production
          command: npm run build
      - persist_to_workspace:
            root: .
            paths:
              - dist
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Firebase Tools
          command: npm install firebase-tools
      - run:
          name: Deploy to firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build
          filters:
              branches:
                  only: master
