defaults: &defaults
  working_directory: ~/project/vuesportscalendar
  docker:
    - image: circleci/node:8.9-stretch

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
              - vuesportscalendar
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Vue for production
          command: npm run build
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Firebase Tools
          command: npm install firebase-tools
      - run:
          name: Deploy to firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - build:
          requires:
              - install
      - deploy:
          requires:
              - build
          filters:
              branches:
                  only: master
